// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/concept_mapping/service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fconcept_5fmapping_2fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fconcept_5fmapping_2fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto/clarifai/api/resources.pb.h"
#include "proto/utils/request_meta.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fconcept_5fmapping_2fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fconcept_5fmapping_2fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fconcept_5fmapping_2fservice_2eproto;
class ConceptMappingRequest;
class ConceptMappingRequestDefaultTypeInternal;
extern ConceptMappingRequestDefaultTypeInternal _ConceptMappingRequest_default_instance_;
class ConceptMappingResponse;
class ConceptMappingResponseDefaultTypeInternal;
extern ConceptMappingResponseDefaultTypeInternal _ConceptMappingResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ConceptMappingRequest* Arena::CreateMaybeMessage<::ConceptMappingRequest>(Arena*);
template<> ::ConceptMappingResponse* Arena::CreateMaybeMessage<::ConceptMappingResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ConceptMappingRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ConceptMappingRequest) */ {
 public:
  ConceptMappingRequest();
  virtual ~ConceptMappingRequest();

  ConceptMappingRequest(const ConceptMappingRequest& from);
  ConceptMappingRequest(ConceptMappingRequest&& from) noexcept
    : ConceptMappingRequest() {
    *this = ::std::move(from);
  }

  inline ConceptMappingRequest& operator=(const ConceptMappingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConceptMappingRequest& operator=(ConceptMappingRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConceptMappingRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConceptMappingRequest* internal_default_instance() {
    return reinterpret_cast<const ConceptMappingRequest*>(
               &_ConceptMappingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ConceptMappingRequest& a, ConceptMappingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ConceptMappingRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConceptMappingRequest* New() const final {
    return CreateMaybeMessage<ConceptMappingRequest>(nullptr);
  }

  ConceptMappingRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConceptMappingRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConceptMappingRequest& from);
  void MergeFrom(const ConceptMappingRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConceptMappingRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ConceptMappingRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fconcept_5fmapping_2fservice_2eproto);
    return ::descriptor_table_proto_2fconcept_5fmapping_2fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConceptIdsFieldNumber = 3,
    kAppIdFieldNumber = 2,
    kMetaFieldNumber = 1,
    kKnowledgeGraphFieldNumber = 4,
  };
  // repeated string concept_ids = 3;
  int concept_ids_size() const;
  void clear_concept_ids();
  const std::string& concept_ids(int index) const;
  std::string* mutable_concept_ids(int index);
  void set_concept_ids(int index, const std::string& value);
  void set_concept_ids(int index, std::string&& value);
  void set_concept_ids(int index, const char* value);
  void set_concept_ids(int index, const char* value, size_t size);
  std::string* add_concept_ids();
  void add_concept_ids(const std::string& value);
  void add_concept_ids(std::string&& value);
  void add_concept_ids(const char* value);
  void add_concept_ids(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& concept_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_concept_ids();

  // string app_id = 2;
  void clear_app_id();
  const std::string& app_id() const;
  void set_app_id(const std::string& value);
  void set_app_id(std::string&& value);
  void set_app_id(const char* value);
  void set_app_id(const char* value, size_t size);
  std::string* mutable_app_id();
  std::string* release_app_id();
  void set_allocated_app_id(std::string* app_id);

  // .RequestMeta meta = 1;
  bool has_meta() const;
  void clear_meta();
  const ::RequestMeta& meta() const;
  ::RequestMeta* release_meta();
  ::RequestMeta* mutable_meta();
  void set_allocated_meta(::RequestMeta* meta);

  // .clarifai.api.KnowledgeGraph knowledge_graph = 4;
  bool has_knowledge_graph() const;
  void clear_knowledge_graph();
  const ::clarifai::api::KnowledgeGraph& knowledge_graph() const;
  ::clarifai::api::KnowledgeGraph* release_knowledge_graph();
  ::clarifai::api::KnowledgeGraph* mutable_knowledge_graph();
  void set_allocated_knowledge_graph(::clarifai::api::KnowledgeGraph* knowledge_graph);

  // @@protoc_insertion_point(class_scope:ConceptMappingRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> concept_ids_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_id_;
  ::RequestMeta* meta_;
  ::clarifai::api::KnowledgeGraph* knowledge_graph_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fconcept_5fmapping_2fservice_2eproto;
};
// -------------------------------------------------------------------

class ConceptMappingResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ConceptMappingResponse) */ {
 public:
  ConceptMappingResponse();
  virtual ~ConceptMappingResponse();

  ConceptMappingResponse(const ConceptMappingResponse& from);
  ConceptMappingResponse(ConceptMappingResponse&& from) noexcept
    : ConceptMappingResponse() {
    *this = ::std::move(from);
  }

  inline ConceptMappingResponse& operator=(const ConceptMappingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConceptMappingResponse& operator=(ConceptMappingResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConceptMappingResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConceptMappingResponse* internal_default_instance() {
    return reinterpret_cast<const ConceptMappingResponse*>(
               &_ConceptMappingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ConceptMappingResponse& a, ConceptMappingResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ConceptMappingResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConceptMappingResponse* New() const final {
    return CreateMaybeMessage<ConceptMappingResponse>(nullptr);
  }

  ConceptMappingResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConceptMappingResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConceptMappingResponse& from);
  void MergeFrom(const ConceptMappingResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConceptMappingResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ConceptMappingResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fconcept_5fmapping_2fservice_2eproto);
    return ::descriptor_table_proto_2fconcept_5fmapping_2fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
  };
  // .ResponseStatus status = 1;
  bool has_status() const;
  void clear_status();
  const ::ResponseStatus& status() const;
  ::ResponseStatus* release_status();
  ::ResponseStatus* mutable_status();
  void set_allocated_status(::ResponseStatus* status);

  // @@protoc_insertion_point(class_scope:ConceptMappingResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::ResponseStatus* status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fconcept_5fmapping_2fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConceptMappingRequest

// .RequestMeta meta = 1;
inline bool ConceptMappingRequest::has_meta() const {
  return this != internal_default_instance() && meta_ != nullptr;
}
inline const ::RequestMeta& ConceptMappingRequest::meta() const {
  const ::RequestMeta* p = meta_;
  // @@protoc_insertion_point(field_get:ConceptMappingRequest.meta)
  return p != nullptr ? *p : *reinterpret_cast<const ::RequestMeta*>(
      &::_RequestMeta_default_instance_);
}
inline ::RequestMeta* ConceptMappingRequest::release_meta() {
  // @@protoc_insertion_point(field_release:ConceptMappingRequest.meta)
  
  ::RequestMeta* temp = meta_;
  meta_ = nullptr;
  return temp;
}
inline ::RequestMeta* ConceptMappingRequest::mutable_meta() {
  
  if (meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::RequestMeta>(GetArenaNoVirtual());
    meta_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ConceptMappingRequest.meta)
  return meta_;
}
inline void ConceptMappingRequest::set_allocated_meta(::RequestMeta* meta) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(meta_);
  }
  if (meta) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      meta = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:ConceptMappingRequest.meta)
}

// string app_id = 2;
inline void ConceptMappingRequest::clear_app_id() {
  app_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ConceptMappingRequest::app_id() const {
  // @@protoc_insertion_point(field_get:ConceptMappingRequest.app_id)
  return app_id_.GetNoArena();
}
inline void ConceptMappingRequest::set_app_id(const std::string& value) {
  
  app_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ConceptMappingRequest.app_id)
}
inline void ConceptMappingRequest::set_app_id(std::string&& value) {
  
  app_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ConceptMappingRequest.app_id)
}
inline void ConceptMappingRequest::set_app_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  app_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ConceptMappingRequest.app_id)
}
inline void ConceptMappingRequest::set_app_id(const char* value, size_t size) {
  
  app_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ConceptMappingRequest.app_id)
}
inline std::string* ConceptMappingRequest::mutable_app_id() {
  
  // @@protoc_insertion_point(field_mutable:ConceptMappingRequest.app_id)
  return app_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ConceptMappingRequest::release_app_id() {
  // @@protoc_insertion_point(field_release:ConceptMappingRequest.app_id)
  
  return app_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ConceptMappingRequest::set_allocated_app_id(std::string* app_id) {
  if (app_id != nullptr) {
    
  } else {
    
  }
  app_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app_id);
  // @@protoc_insertion_point(field_set_allocated:ConceptMappingRequest.app_id)
}

// repeated string concept_ids = 3;
inline int ConceptMappingRequest::concept_ids_size() const {
  return concept_ids_.size();
}
inline void ConceptMappingRequest::clear_concept_ids() {
  concept_ids_.Clear();
}
inline const std::string& ConceptMappingRequest::concept_ids(int index) const {
  // @@protoc_insertion_point(field_get:ConceptMappingRequest.concept_ids)
  return concept_ids_.Get(index);
}
inline std::string* ConceptMappingRequest::mutable_concept_ids(int index) {
  // @@protoc_insertion_point(field_mutable:ConceptMappingRequest.concept_ids)
  return concept_ids_.Mutable(index);
}
inline void ConceptMappingRequest::set_concept_ids(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:ConceptMappingRequest.concept_ids)
  concept_ids_.Mutable(index)->assign(value);
}
inline void ConceptMappingRequest::set_concept_ids(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:ConceptMappingRequest.concept_ids)
  concept_ids_.Mutable(index)->assign(std::move(value));
}
inline void ConceptMappingRequest::set_concept_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  concept_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ConceptMappingRequest.concept_ids)
}
inline void ConceptMappingRequest::set_concept_ids(int index, const char* value, size_t size) {
  concept_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ConceptMappingRequest.concept_ids)
}
inline std::string* ConceptMappingRequest::add_concept_ids() {
  // @@protoc_insertion_point(field_add_mutable:ConceptMappingRequest.concept_ids)
  return concept_ids_.Add();
}
inline void ConceptMappingRequest::add_concept_ids(const std::string& value) {
  concept_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ConceptMappingRequest.concept_ids)
}
inline void ConceptMappingRequest::add_concept_ids(std::string&& value) {
  concept_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ConceptMappingRequest.concept_ids)
}
inline void ConceptMappingRequest::add_concept_ids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  concept_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ConceptMappingRequest.concept_ids)
}
inline void ConceptMappingRequest::add_concept_ids(const char* value, size_t size) {
  concept_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ConceptMappingRequest.concept_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ConceptMappingRequest::concept_ids() const {
  // @@protoc_insertion_point(field_list:ConceptMappingRequest.concept_ids)
  return concept_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ConceptMappingRequest::mutable_concept_ids() {
  // @@protoc_insertion_point(field_mutable_list:ConceptMappingRequest.concept_ids)
  return &concept_ids_;
}

// .clarifai.api.KnowledgeGraph knowledge_graph = 4;
inline bool ConceptMappingRequest::has_knowledge_graph() const {
  return this != internal_default_instance() && knowledge_graph_ != nullptr;
}
inline const ::clarifai::api::KnowledgeGraph& ConceptMappingRequest::knowledge_graph() const {
  const ::clarifai::api::KnowledgeGraph* p = knowledge_graph_;
  // @@protoc_insertion_point(field_get:ConceptMappingRequest.knowledge_graph)
  return p != nullptr ? *p : *reinterpret_cast<const ::clarifai::api::KnowledgeGraph*>(
      &::clarifai::api::_KnowledgeGraph_default_instance_);
}
inline ::clarifai::api::KnowledgeGraph* ConceptMappingRequest::release_knowledge_graph() {
  // @@protoc_insertion_point(field_release:ConceptMappingRequest.knowledge_graph)
  
  ::clarifai::api::KnowledgeGraph* temp = knowledge_graph_;
  knowledge_graph_ = nullptr;
  return temp;
}
inline ::clarifai::api::KnowledgeGraph* ConceptMappingRequest::mutable_knowledge_graph() {
  
  if (knowledge_graph_ == nullptr) {
    auto* p = CreateMaybeMessage<::clarifai::api::KnowledgeGraph>(GetArenaNoVirtual());
    knowledge_graph_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ConceptMappingRequest.knowledge_graph)
  return knowledge_graph_;
}
inline void ConceptMappingRequest::set_allocated_knowledge_graph(::clarifai::api::KnowledgeGraph* knowledge_graph) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(knowledge_graph_);
  }
  if (knowledge_graph) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      knowledge_graph = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, knowledge_graph, submessage_arena);
    }
    
  } else {
    
  }
  knowledge_graph_ = knowledge_graph;
  // @@protoc_insertion_point(field_set_allocated:ConceptMappingRequest.knowledge_graph)
}

// -------------------------------------------------------------------

// ConceptMappingResponse

// .ResponseStatus status = 1;
inline bool ConceptMappingResponse::has_status() const {
  return this != internal_default_instance() && status_ != nullptr;
}
inline const ::ResponseStatus& ConceptMappingResponse::status() const {
  const ::ResponseStatus* p = status_;
  // @@protoc_insertion_point(field_get:ConceptMappingResponse.status)
  return p != nullptr ? *p : *reinterpret_cast<const ::ResponseStatus*>(
      &::_ResponseStatus_default_instance_);
}
inline ::ResponseStatus* ConceptMappingResponse::release_status() {
  // @@protoc_insertion_point(field_release:ConceptMappingResponse.status)
  
  ::ResponseStatus* temp = status_;
  status_ = nullptr;
  return temp;
}
inline ::ResponseStatus* ConceptMappingResponse::mutable_status() {
  
  if (status_ == nullptr) {
    auto* p = CreateMaybeMessage<::ResponseStatus>(GetArenaNoVirtual());
    status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ConceptMappingResponse.status)
  return status_;
}
inline void ConceptMappingResponse::set_allocated_status(::ResponseStatus* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(status_);
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    
  } else {
    
  }
  status_ = status;
  // @@protoc_insertion_point(field_set_allocated:ConceptMappingResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fconcept_5fmapping_2fservice_2eproto
