// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/concept_mapping/service.proto
#ifndef GRPC_proto_2fconcept_5fmapping_2fservice_2eproto__INCLUDED
#define GRPC_proto_2fconcept_5fmapping_2fservice_2eproto__INCLUDED

#include "proto/concept_mapping/service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

// Interface exported by the server.
class ConceptMappingService final {
 public:
  static constexpr char const* service_full_name() {
    return "ConceptMappingService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Maps the given concepts
    virtual ::grpc::Status MapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::ConceptMappingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConceptMappingResponse>> AsyncMapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConceptMappingResponse>>(AsyncMapConceptsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConceptMappingResponse>> PrepareAsyncMapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConceptMappingResponse>>(PrepareAsyncMapConceptsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Maps the given concepts
      virtual void MapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MapConcepts(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConceptMappingResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void MapConcepts(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConceptMappingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ConceptMappingResponse>* AsyncMapConceptsRaw(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ConceptMappingResponse>* PrepareAsyncMapConceptsRaw(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status MapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::ConceptMappingResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConceptMappingResponse>> AsyncMapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConceptMappingResponse>>(AsyncMapConceptsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConceptMappingResponse>> PrepareAsyncMapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConceptMappingResponse>>(PrepareAsyncMapConceptsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void MapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response, std::function<void(::grpc::Status)>) override;
      void MapConcepts(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConceptMappingResponse* response, std::function<void(::grpc::Status)>) override;
      void MapConcepts(::grpc::ClientContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void MapConcepts(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConceptMappingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ConceptMappingResponse>* AsyncMapConceptsRaw(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ConceptMappingResponse>* PrepareAsyncMapConceptsRaw(::grpc::ClientContext* context, const ::ConceptMappingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MapConcepts_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Maps the given concepts
    virtual ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_MapConcepts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_MapConcepts() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MapConcepts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapConcepts(::grpc::ServerContext* context, ::ConceptMappingRequest* request, ::grpc::ServerAsyncResponseWriter< ::ConceptMappingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MapConcepts<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_MapConcepts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_MapConcepts() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::ConceptMappingRequest, ::ConceptMappingResponse>(
          [this](::grpc::ServerContext* context,
                 const ::ConceptMappingRequest* request,
                 ::ConceptMappingResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->MapConcepts(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_MapConcepts(
        ::grpc::experimental::MessageAllocator< ::ConceptMappingRequest, ::ConceptMappingResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::ConceptMappingRequest, ::ConceptMappingResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_MapConcepts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_MapConcepts<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MapConcepts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_MapConcepts() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MapConcepts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MapConcepts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_MapConcepts() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MapConcepts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapConcepts(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_MapConcepts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_MapConcepts() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->MapConcepts(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_MapConcepts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void MapConcepts(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MapConcepts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_MapConcepts() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ConceptMappingRequest, ::ConceptMappingResponse>(std::bind(&WithStreamedUnaryMethod_MapConcepts<BaseClass>::StreamedMapConcepts, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_MapConcepts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MapConcepts(::grpc::ServerContext* context, const ::ConceptMappingRequest* request, ::ConceptMappingResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMapConcepts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ConceptMappingRequest,::ConceptMappingResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MapConcepts<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MapConcepts<Service > StreamedService;
};


#endif  // GRPC_proto_2fconcept_5fmapping_2fservice_2eproto__INCLUDED
