name: Linux

on:
  push:
    branches:
    - '*'
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    tags-ignore:
    - '*.*'
  pull_request:
    types: [opened, reopened]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v1

      # CACHE
    - id: ccache-cache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache

    - name: configure
      run: cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug

    - name: collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

    - run: ccache -s
