name: Linux

on:
  push:
    branches:
    - '*'
    paths-ignore:
    - 'docs/**'
    - '**/README.md'
    tags-ignore:
    - '*.*'
  pull_request:
    types: [opened, reopened]

env:
  BUILD_TYPE: Debug
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v1

    - run: scripts/ci/actions-install-linux.sh
    - run: git submodule update --init --recursive

      # CACHE
    - id: ccache-cache
      uses: actions/cache@v1
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache

    - name: build
      run: |
        mkdir build && cd build
        ulimit -c unlimited -S
        cmake .. -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCODE_COVERAGE=ON
        make -j$(nproc)

    - name: test
      run: |
        cd build
        make test ARGS=-V
        "../scripts/ci/get_code_cov.sh" "${PWD}"

    - name: collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

    - run: ccache -s
